import { PostTemplate, AspectRatioKey, AspectRatioConfig } from '../types';

export const aspectRatios: Record<AspectRatioKey, AspectRatioConfig> = {
  '4:5':  { nativeW: 1080, nativeH: 1350, px: '1080 × 1350 px', label: 'Instagram 4:5 (Vertical)' },
  '1:1':  { nativeW: 1080, nativeH: 1080, px: '1080 × 1080 px', label: 'Cuadrado 1:1 (Post)' },
  '9:16': { nativeW: 1080, nativeH: 1920, px: '1080 × 1920 px', label: 'Story / Reel 9:16' },
  '16:9': { nativeW: 1920, nativeH: 1080, px: '1920 × 1080 px', label: 'Landscape 16:9 (Banner)' },
};

export const defaultTemplates: PostTemplate[] = [
  // 1. Desarrollo a la Medida (t1 a t6)
  {
    id: "t1",
    category: "DESARROLLO A LA MEDIDA",
    color: "#4F46E5",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "¿Tu empresa ya superó a Excel? 3 señales de que necesitas un panel propio",
    titleSize: 48,
    titleColor: "contrast",
    subtitle: "Centraliza pedidos, inventarios y permisos en una sola plataforma web en la nube sin errores de fórmula.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "code",
    code: "system.migrate({ from: 'Inventario_Final_v3.xlsx', to: 'CloudDB' });",
    tags: "PostgreSQL, Next.js, FastAPI, Roles Seguros",
    bgPattern: "circuit",
    patternScale: 100,
    patternVignette: "vignette",
    accentShape: "glow",
    shapeSizeVariant: "medium",
    lightDirection: "dual-corners-1",
    lightIntensity: 40,
    headerShape: "line",
    footerShape: "line",
    cta: "Escríbenos y migramos tu operación a la nube.",
    handle: "aleric.dev"
  },
  {
    id: "t2",
    category: "DESARROLLO A LA MEDIDA",
    color: "#4F46E5",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "¿Sabías que cualquiera puede descargar tu base de datos en Excel?",
    titleSize: 46,
    titleColor: "contrast",
    subtitle: "Las hojas de cálculo tienen cero seguridad por roles. Protege la información confidencial de tu empresa con bases de datos blindadas.",
    subtitleSize: 22,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "code",
    code: "auth.require_role(['ADMIN', 'DIRECTOR_FINANCIERO']);",
    tags: "Ciberseguridad, RBAC, PostgreSQL, JWT",
    bgPattern: "circuit",
    patternScale: 90,
    patternVignette: "gradient-top",
    accentShape: "diamonds",
    shapeSizeVariant: "medium",
    lightDirection: "dual-corners-1",
    lightIntensity: 35,
    headerShape: "pill",
    footerShape: "line",
    cta: "Blindaje de datos corporativos con Aleric Dev.",
    handle: "aleric.dev"
  },
  {
    id: "t3",
    category: "DESARROLLO A LA MEDIDA",
    color: "#4F46E5",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "MVP Express: De la idea a tu software en producción en 3 semanas",
    titleSize: 48,
    titleColor: "contrast",
    subtitle: "No necesitas un desarrollo de 8 meses para validar tu negocio. Diseñamos plataformas ágiles y listas para escalar.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "compact",
    module: "kpi",
    tags: "FastAPI, React 19, Supabase, Cloudflare",
    bgPattern: "matrix",
    patternScale: 80,
    patternVignette: "vignette",
    accentShape: "circles",
    shapeSizeVariant: "large",
    lightDirection: "top",
    lightIntensity: 45,
    headerShape: "line",
    footerShape: "card",
    cta: "Lanza tu producto al mercado antes que la competencia.",
    handle: "aleric.dev"
  },
  {
    id: "t4",
    category: "DESARROLLO A LA MEDIDA",
    color: "#4F46E5",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "Por qué las apps en WordPress colapsan cuando tu empresa crece",
    titleSize: 46,
    titleColor: "contrast",
    subtitle: "Los plugins masivos generan lentitud y agujeros de seguridad. La arquitectura desacoplada garantiza escalabilidad infinita.",
    subtitleSize: 22,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "code",
    code: "const api = new Architecture({ decoupling: true, memory: '100% optimized' });",
    tags: "Clean Architecture, NestJS, Headless, Cero Bloatware",
    bgPattern: "hexagons",
    patternScale: 110,
    patternVignette: "gradient-bottom",
    accentShape: "squares",
    shapeSizeVariant: "medium",
    lightDirection: "dual-corners-2",
    lightIntensity: 35,
    headerShape: "line",
    footerShape: "line",
    cta: "Construimos software que soporta millones de transacciones.",
    handle: "aleric.dev"
  },
  {
    id: "t5",
    category: "DESARROLLO A LA MEDIDA",
    color: "#4F46E5",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "Automatiza la facturación electrónica directamente con la DIAN",
    titleSize: 48,
    titleColor: "contrast",
    subtitle: "Emite facturas XML firmadas en milisegundos sin pagar intermediarios mensuales por cada comprobante.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "code",
    code: "dian.issue_invoice({ invoice_id: 1042, certified: True });",
    tags: "Facturación Electrónica, XML, Firma Digital, API DIAN",
    bgPattern: "circuit",
    patternScale: 95,
    patternVignette: "vignette",
    accentShape: "glow",
    shapeSizeVariant: "medium",
    lightDirection: "bottom",
    lightIntensity: 40,
    headerShape: "card",
    footerShape: "line",
    cta: "Conecta tu software a la DIAN de forma transparente.",
    handle: "aleric.dev"
  },
  {
    id: "t6",
    category: "DESARROLLO A LA MEDIDA",
    color: "#4F46E5",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "El costo oculto del software heredado en tu empresa",
    titleSize: 50,
    titleColor: "contrast",
    subtitle: "Cada parche temporal aumenta la deuda técnica y bloquea la innovación. Modernizamos tu stack sin frenar tu operación.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: false,
    moduleSize: "normal",
    module: "code",
    tags: "Modernización, Refactorización, Zero Downtime, Microservicios",
    bgPattern: "neural",
    patternScale: 120,
    patternVignette: "vignette",
    accentShape: "circles",
    shapeSizeVariant: "large",
    lightDirection: "center",
    lightIntensity: 50,
    headerShape: "line",
    footerShape: "line",
    cta: "Da el salto a la infraestructura cloud moderna hoy.",
    handle: "aleric.dev"
  },

  // 2. Landing Pages & Web Speed (t7 a t12)
  {
    id: "t7",
    category: "LANDING PAGES / WEB SPEED",
    color: "#0891B2",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "Estás pagando pauta publicitaria para rebotar clientes por lentitud",
    titleSize: 46,
    titleColor: "contrast",
    subtitle: "Cada segundo extra que tarda tu web en cargar reduce tus ventas en un 7%. Optimizamos tu landing para 95+ en Google Lighthouse.",
    subtitleSize: 22,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "kpi",
    tags: "Google Lighthouse, Core Web Vitals, Astro, Tailwind",
    bgPattern: "hexagons",
    patternScale: 100,
    patternVignette: "vignette",
    accentShape: "glow",
    shapeSizeVariant: "medium",
    lightDirection: "dual-corners-1",
    lightIntensity: 40,
    headerShape: "line",
    footerShape: "line",
    cta: "Hacemos una auditoría gratuita de velocidad a tu web actual.",
    handle: "aleric.dev"
  },
  {
    id: "t8",
    category: "LANDING PAGES / WEB SPEED",
    color: "#0891B2",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "La regla de los 5 segundos: Si tu visitante no entiende tu oferta, se va",
    titleSize: 48,
    titleColor: "contrast",
    subtitle: "Reemplaza los títulos abstractos por mensajes contundentes que conviertan visitas en clientes cualificados.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "chart",
    tags: "Copywriting B2B, UI/UX Premium, CRO, Astro",
    bgPattern: "isometric",
    patternScale: 110,
    patternVignette: "gradient-top",
    accentShape: "circles",
    shapeSizeVariant: "medium",
    lightDirection: "top",
    lightIntensity: 35,
    headerShape: "pill",
    footerShape: "line",
    cta: "Diseñamos interfaces que cautivan y venden.",
    handle: "aleric.dev"
  },
  {
    id: "t9",
    category: "LANDING PAGES / WEB SPEED",
    color: "#0891B2",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "Por qué tus anuncios de Meta Ads no convierten en tu web",
    titleSize: 48,
    titleColor: "contrast",
    subtitle: "El anuncio engancha, pero el prospecto llega a una web lenta, confusa y sin llamada a la acción clara.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "chart",
    tags: "Optimización CRO, Funnels de Venta, Speed 99/100",
    bgPattern: "hexagons",
    patternScale: 90,
    patternVignette: "vignette",
    accentShape: "glow",
    shapeSizeVariant: "medium",
    lightDirection: "dual-corners-2",
    lightIntensity: 40,
    headerShape: "line",
    footerShape: "card",
    cta: "Haz rentable cada dólar invertido en publicidad.",
    handle: "aleric.dev"
  },
  {
    id: "t10",
    category: "LANDING PAGES / WEB SPEED",
    color: "#0891B2",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "0.4 segundos: La diferencia entre un cliente cautivado y un rebote",
    titleSize: 46,
    titleColor: "contrast",
    subtitle: "Desplegamos en la red perimetral Edge de Cloudflare para que tu web abra al instante desde cualquier país.",
    subtitleSize: 22,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "compact",
    module: "kpi",
    tags: "Cloudflare Edge, TTFB < 50ms, HTTP/3, Brotli",
    bgPattern: "waves",
    patternScale: 100,
    patternVignette: "gradient-bottom",
    accentShape: "lines",
    shapeSizeVariant: "large",
    lightDirection: "sides",
    lightIntensity: 35,
    headerShape: "line",
    footerShape: "line",
    cta: "Acelera tu presencia comercial a la velocidad de la luz.",
    handle: "aleric.dev"
  },
  {
    id: "t11",
    category: "LANDING PAGES / WEB SPEED",
    color: "#0891B2",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "Cero JavaScript innecesario: La filosofía de alto rendimiento",
    titleSize: 48,
    titleColor: "contrast",
    subtitle: "El 80% del código en las webs comerciales sobra. Eliminamos el bloatware para lograr una navegación ultraligera.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "code",
    code: "bundle.optimize({ islands_only: true, zero_bloatware: true });",
    tags: "Astro Islands, Minimal JS, SEO Técnico, WCAG AAA",
    bgPattern: "matrix",
    patternScale: 85,
    patternVignette: "vignette",
    accentShape: "glow",
    shapeSizeVariant: "medium",
    lightDirection: "dual-corners-1",
    lightIntensity: 40,
    headerShape: "line",
    footerShape: "line",
    cta: "Construimos webs sin peso muerto que convierten visitantes en clientes.",
    handle: "aleric.dev"
  },
  {
    id: "t12",
    category: "LANDING PAGES / WEB SPEED",
    color: "#0891B2",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "Tu landing page es el mejor vendedor de tu empresa: 24/7 sin descanso",
    titleSize: 50,
    titleColor: "contrast",
    subtitle: "Una experiencia estética premium genera confianza inmediata y justifica precios más altos para tus servicios.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: false,
    moduleSize: "normal",
    module: "chart",
    tags: "Branding Tech, Posicionamiento Premium, High Ticket",
    bgPattern: "dots",
    patternScale: 60,
    patternVignette: "mask-center",
    accentShape: "circles",
    shapeSizeVariant: "large",
    lightDirection: "center",
    lightIntensity: 45,
    headerShape: "pill",
    footerShape: "line",
    cta: "Eleva el estatus visual de tu negocio en internet.",
    handle: "aleric.dev"
  },

  // 3. Automatización & WhatsApp (t13 a t18)
  {
    id: "t13",
    category: "AUTOMATIZACIÓN & WHATSAPP",
    color: "#059669",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "El mensaje de WhatsApp que le costó $2.000 USD a una empresa",
    titleSize: 46,
    titleColor: "contrast",
    subtitle: "Tardar 30 minutos en responder una consulta caliente es regalarle la venta a la competencia.",
    subtitleSize: 22,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "chat",
    tags: "WhatsApp Cloud API, n8n, Meta Verified, CRM",
    bgPattern: "circuit",
    patternScale: 100,
    patternVignette: "vignette",
    accentShape: "glow",
    shapeSizeVariant: "medium",
    lightDirection: "dual-corners-1",
    lightIntensity: 40,
    headerShape: "line",
    footerShape: "line",
    cta: "Automatiza la atención de tu negocio con Aleric Dev.",
    handle: "aleric.dev"
  },
  {
    id: "t14",
    category: "AUTOMATIZACIÓN & WHATSAPP",
    color: "#059669",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "4 tareas que tu vendedor no debería estar haciendo a mano",
    titleSize: 48,
    titleColor: "contrast",
    subtitle: "Enviar cuentas bancarias, recordar citas, cotizar precios estándar y calificar prospectos fríos.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "chat",
    tags: "Automatización, WhatsApp API, Webhooks, CRM",
    bgPattern: "neural",
    patternScale: 105,
    patternVignette: "gradient-top",
    accentShape: "circles",
    shapeSizeVariant: "medium",
    lightDirection: "top",
    lightIntensity: 35,
    headerShape: "card",
    footerShape: "line",
    cta: "Deja que la tecnología venda mientras tú lideras.",
    handle: "aleric.dev"
  },
  {
    id: "t15",
    category: "AUTOMATIZACIÓN & WHATSAPP",
    color: "#059669",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "Bandeja multiagente: 1 solo número de WhatsApp para todo tu equipo",
    titleSize: 46,
    titleColor: "contrast",
    subtitle: "Deja de pasarte el celular físico por la oficina. Conecta a todo tu equipo de ventas a una sola línea oficial con historial compartido.",
    subtitleSize: 22,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "chat",
    tags: "Multiagente, WhatsApp Cloud API, Atención Omnicanal",
    bgPattern: "circuit",
    patternScale: 95,
    patternVignette: "vignette",
    accentShape: "glow",
    shapeSizeVariant: "medium",
    lightDirection: "dual-corners-2",
    lightIntensity: 40,
    headerShape: "line",
    footerShape: "line",
    cta: "Transforma tu canal de ventas por WhatsApp.",
    handle: "aleric.dev"
  },
  {
    id: "t16",
    category: "AUTOMATIZACIÓN & WHATSAPP",
    color: "#059669",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "Agentes IA en WhatsApp que realmente cierran ventas",
    titleSize: 48,
    titleColor: "contrast",
    subtitle: "Nada de respuestas robóticas. Conectamos modelos de lenguaje entrenados con tu catálogo para resolver dudas complejas en segundos.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "chat",
    tags: "IA Conversacional, LLMs, RAG, WhatsApp API",
    bgPattern: "neural",
    patternScale: 110,
    patternVignette: "mask-center",
    accentShape: "diamonds",
    shapeSizeVariant: "medium",
    lightDirection: "bottom",
    lightIntensity: 45,
    headerShape: "pill",
    footerShape: "line",
    cta: "Convierte WhatsApp en tu máquina de ventas automática.",
    handle: "aleric.dev"
  },
  {
    id: "t17",
    category: "AUTOMATIZACIÓN & WHATSAPP",
    color: "#059669",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "Sincroniza tus pedidos de la tienda online con tu inventario físico",
    titleSize: 46,
    titleColor: "contrast",
    subtitle: "Cada venta en tu web o marketplace descuenta stock y alerta a tu equipo de despacho al instante sin doble digitación.",
    subtitleSize: 22,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "compact",
    module: "kpi",
    tags: "Integración ERP, Webhooks, n8n, E-commerce",
    bgPattern: "matrix",
    patternScale: 90,
    patternVignette: "gradient-bottom",
    accentShape: "squares",
    shapeSizeVariant: "small",
    lightDirection: "four-corners",
    lightIntensity: 35,
    headerShape: "line",
    footerShape: "card",
    cta: "Cero errores de inventario con flujos automatizados.",
    handle: "aleric.dev"
  },
  {
    id: "t18",
    category: "AUTOMATIZACIÓN & WHATSAPP",
    color: "#059669",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "El 70% de tus prospectos compran al negocio que responde primero",
    titleSize: 50,
    titleColor: "contrast",
    subtitle: "La velocidad de respuesta es la métrica reina del comercio moderno. No dejes que tus leads se enfríen por falta de un bot inteligente.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: false,
    moduleSize: "normal",
    module: "chat",
    tags: "Lead Scoring, WhatsApp Bots, Cierre Automático",
    bgPattern: "waves",
    patternScale: 115,
    patternVignette: "vignette",
    accentShape: "circles",
    shapeSizeVariant: "large",
    lightDirection: "center",
    lightIntensity: 50,
    headerShape: "line",
    footerShape: "line",
    cta: "Atención inmediata para cada cliente potencial.",
    handle: "aleric.dev"
  },

  // 4. Consultoría & Estrategia (t19 a t24)
  {
    id: "t19",
    category: "CONSULTORÍA / ESTRATEGIA",
    color: "#D97706",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "La trampa de pagar suscripciones mensuales de automatización",
    titleSize: 46,
    titleColor: "contrast",
    subtitle: "Zapier te cobra por cada tarea ejecutada. Con n8n en servidor propio tus flujos son ilimitados y 100% tuyos.",
    subtitleSize: 22,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "code",
    code: "system.migrate({ from: 'Zapier_Cloud_Plan', to: 'Self_Hosted_n8n' });",
    tags: "n8n Self-Hosted, Docker, Linux, Ahorro SaaS",
    bgPattern: "matrix",
    patternScale: 90,
    patternVignette: "vignette",
    accentShape: "diamonds",
    shapeSizeVariant: "medium",
    lightDirection: "dual-corners-1",
    lightIntensity: 40,
    headerShape: "line",
    footerShape: "line",
    cta: "Soberanía digital con código 100% de tu propiedad.",
    handle: "aleric.dev"
  },
  {
    id: "t20",
    category: "CONSULTORÍA / ESTRATEGIA",
    color: "#D97706",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "En Aleric no nos quedamos con tu código: Tuyo al 100%",
    titleSize: 48,
    titleColor: "contrast",
    subtitle: "Te entregamos los repositorios a tu nombre, documentación técnica completa y cero contratos de amarre.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "compact",
    module: "kpi",
    tags: "Propiedad Intelectual, GitHub, Docker, Cero Amarre",
    bgPattern: "matrix",
    patternScale: 95,
    patternVignette: "gradient-top",
    accentShape: "glow",
    shapeSizeVariant: "medium",
    lightDirection: "top",
    lightIntensity: 35,
    headerShape: "card",
    footerShape: "line",
    cta: "Ingeniería transparente y relaciones a largo plazo.",
    handle: "aleric.dev"
  },
  {
    id: "t21",
    category: "CONSULTORÍA / ESTRATEGIA",
    color: "#D97706",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "Hablar con el programador vs. Hablar con un intermediario comercial",
    titleSize: 46,
    titleColor: "contrast",
    subtitle: "En Aleric trabajas mano a mano con ingenieros sénior sin intermediarios comerciales que prometan imposibles.",
    subtitleSize: 22,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "code",
    code: "team.connect(client_cto, senior_engineer, direct_channel=True);",
    tags: "Ingeniería Sénior, Comunicación Directa, Cero Burocracia",
    bgPattern: "neural",
    patternScale: 100,
    patternVignette: "vignette",
    accentShape: "circles",
    shapeSizeVariant: "medium",
    lightDirection: "dual-corners-2",
    lightIntensity: 40,
    headerShape: "pill",
    footerShape: "line",
    cta: "Ingeniería directa sin teléfonos rotos.",
    handle: "aleric.dev"
  },
  {
    id: "t22",
    category: "CONSULTORÍA / ESTRATEGIA",
    color: "#D97706",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "Auditoría de Arquitectura: Descubre fugas de dinero en tu nube",
    titleSize: 48,
    titleColor: "contrast",
    subtitle: "Instancias sobredimensionadas, bases de datos sin índices y servicios duplicados. Reducimos tu factura de AWS/GCP hasta un 50%.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "normal",
    module: "chart",
    tags: "FinOps, Optimización Cloud, AWS, GCP",
    bgPattern: "topographic",
    patternScale: 110,
    patternVignette: "mask-center",
    accentShape: "lines",
    shapeSizeVariant: "large",
    lightDirection: "bottom",
    lightIntensity: 40,
    headerShape: "line",
    footerShape: "card",
    cta: "Optimiza tu inversión tecnológica con ingeniería real.",
    handle: "aleric.dev"
  },
  {
    id: "t23",
    category: "CONSULTORÍA / ESTRATEGIA",
    color: "#D97706",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "Por qué tu empresa necesita un CTO As-A-Service",
    titleSize: 48,
    titleColor: "contrast",
    subtitle: "Accede al liderazgo técnico de un director de ingeniería sénior sin incurrir en el salario fijo de tiempo completo.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: true,
    moduleSize: "compact",
    module: "kpi",
    tags: "CTO Fractional, Estrategia Tech, Gobernanza TI",
    bgPattern: "hexagons",
    patternScale: 105,
    patternVignette: "gradient-bottom",
    accentShape: "squares",
    shapeSizeVariant: "medium",
    lightDirection: "sides",
    lightIntensity: 35,
    headerShape: "line",
    footerShape: "line",
    cta: "Toma decisiones de software respaldadas por expertos.",
    handle: "aleric.dev"
  },
  {
    id: "t24",
    category: "CONSULTORÍA / ESTRATEGIA",
    color: "#D97706",
    companyName: "Aleric Dev",
    logoType: "generic",
    title: "El software no se compra por metro: Se diseña para resolver cuellos de botella",
    titleSize: 50,
    titleColor: "contrast",
    subtitle: "La tecnología que no ahorra horas de trabajo o no incrementa las ventas es un gasto estéril. Enfócate en el retorno de inversión.",
    subtitleSize: 24,
    subtitlePos: "below",
    moduleVisible: false,
    moduleSize: "normal",
    module: "code",
    tags: "ROI Tecnológico, Estrategia B2B, Automatización",
    bgPattern: "circuit",
    patternScale: 100,
    patternVignette: "vignette",
    accentShape: "glow",
    shapeSizeVariant: "large",
    lightDirection: "center",
    lightIntensity: 45,
    headerShape: "line",
    footerShape: "line",
    cta: "Construyamos soluciones que hagan crecer tu negocio.",
    handle: "aleric.dev"
  }
];
